# Site settings
title: FIFA World Cup Brazil 2014 | جام جهانی برزیل 2014
email: hi@fifawc.ir
description: "آخرین نتایج مسابقات در جام جهانی برزیل 2014 را می توانید از این وبسایت دنبال کنید."
baseurl: "http://fifawc.ir"
url: "http://fifawc.ir"

# Build settings
markdown: kramdown
permalink: pretty
sass:
    sass_dir: _sass
    style: :compressed